5 acceptance testing
Wcapers/qna pull request #4
Opened 2020-11-16 10:18 UTC by Wcapers

2020-11-17 06:10 UTC, IvanShamatov requested changes
чтобы от конфликта избавиться, нужно зайти в ветку разработки и сделать 
git merge master
после чего нужно зайти в конфликтующий файл, пофиксить конфликт
git add .
git commit -m 'описание коммита'

2020-11-17 06:10 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +      redirect_to @question, notice: t('.failure_create')
тут просто надо рендерить другую страницу, если ты редирект сделаешь, то потеряешь информацию о результатах валидации
render 'questions#show'

2020-11-17 06:10 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    if @question.update(question_params)
тут было бы неплохо проверять, что вопрос обновляет автор, а не абы кто

2020-11-17 06:10 UTC, IvanShamatov commented on app/views/answers/_new.html.slim
> +=render 'shared/errors', resource: @answer
ну вот, паршл с ошибками ты рендеришь, а по факту его бы никогда не увидел

2020-11-17 06:10 UTC, IvanShamatov commented on app/views/questions/_question.html.slim
> +- if current_user && current_user.author_of?(question)
можно использовать safe-оператор
`current_user&.author_of?(question)`
Это аналог `try` в рельсе

2020-11-17 06:10 UTC, IvanShamatov commented on spec/features/question/show_question_spec.rb
> +  describe 'Authenticated user' do
Нету спеки на Update вопроса, поэтому та бага с неавторизованным пользователем и затесалась. Была бы спека, не было бы баги

2020-11-17 14:07 UTC, Wcapers commented on spec/features/question/show_question_spec.rb
> +  describe 'Authenticated user' do
Update не было в задании, я просто поставил на него пустую вьюху и не добавил его в в другие вьюхи. Нужно ли реализовывать его функционал в этом задании?

2020-11-18 06:32 UTC, IvanShamatov approved these changes
Если ты добавляешь экшен, то должна быть и спека, не важно было ли это в задании или нет. Если не хочешь добавлять спеку, не добавляй и логику, которую он проверяет

2020-11-19 20:26 UTC, merged